In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
cd

/home/rafaelincao

In [4]:
df_raw = pd.read_csv('gcj2008.csv')
df_raw.head()

,Unnamed: 0,year,round,username,task,solution,file,full_path,flines
0,0,2008,32002,MikeSeibert,24445,0,EndlessKnight.java,gcj/2008/32002/MikeSeibert/24445/0/extracted/E...,import java.util.Scanner;\n \n public class En...
1,1,2008,32002,MikeSeibert,24444,1,Pockets.java,gcj/2008/32002/MikeSeibert/24444/1/extracted/P...,import java.util.Scanner;\n \n public class Po...
2,2,2008,32002,MikeSeibert,24444,0,Pockets.java,gcj/2008/32002/MikeSeibert/24444/0/extracted/P...,import java.util.Scanner;\n \n public class Po...
3,3,2008,32002,MikeSeibert,24446,0,NoCheating.java,gcj/2008/32002/MikeSeibert/24446/0/extracted/N...,import java.util.Scanner;\n \n public class No...
4,4,2008,32002,bhamrick,24445,0,D.cpp,gcj/2008/32002/bhamrick/24445/0/extracted/D.cpp,#include<cstdio>\n #include<cstdlib>\n \n #def...

In [5]:
df=df_raw.dropna()

In [6]:
df=df[:1000]
df

,Unnamed: 0,year,round,username,task,solution,file,full_path,flines
0,0,2008,32002,MikeSeibert,24445,0,EndlessKnight.java,gcj/2008/32002/MikeSeibert/24445/0/extracted/E...,import java.util.Scanner;\n \n public class En...
1,1,2008,32002,MikeSeibert,24444,1,Pockets.java,gcj/2008/32002/MikeSeibert/24444/1/extracted/P...,import java.util.Scanner;\n \n public class Po...
2,2,2008,32002,MikeSeibert,24444,0,Pockets.java,gcj/2008/32002/MikeSeibert/24444/0/extracted/P...,import java.util.Scanner;\n \n public class Po...
3,3,2008,32002,MikeSeibert,24446,0,NoCheating.java,gcj/2008/32002/MikeSeibert/24446/0/extracted/N...,import java.util.Scanner;\n \n public class No...
4,4,2008,32002,bhamrick,24445,0,D.cpp,gcj/2008/32002/bhamrick/24445/0/extracted/D.cpp,#include<cstdio>\n #include<cstdlib>\n \n #def...
...,...,...,...,...,...,...,...,...,...
995,995,2008,32002,Jonasz,24446,1,C.cpp,gcj/2008/32002/Jonasz/24446/1/extracted/C.cpp,#include<cstdio>\n #include<algorithm>\n using...
996,996,2008,32002,Jonasz,24446,0,C.cpp,gcj/2008/32002/Jonasz/24446/0/extracted/C.cpp,#include<cstdio>\n #include<algorithm>\n using...
997,997,2008,32002,Ragnarok,24445,0,problem.cpp,gcj/2008/32002/Ragnarok/24445/0/extracted/prob...,"// BEGIN CUT HERE\n #include ""stdafx.h""\n // E..."
998,998,2008,32002,Ragnarok,24443,0,problem.cpp,gcj/2008/32002/Ragnarok/24443/0/extracted/prob...,"// BEGIN CUT HERE\n #include ""stdafx.h""\n // E..."
999,999,2008,32002,Ragnarok,24446,0,problem.cpp,gcj/2008/32002/Ragnarok/24446/0/extracted/prob...,"// BEGIN CUT HERE\n #include ""stdafx.h""\n // E..."

In [7]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

target_encoder = LabelEncoder().fit(df['username']) 
y = target_encoder.transform(df['username'])
y

array([ 85,  85,  85,  85, 165, 165, 165, 165, 257, 257, 122, 122, 288,
       288, 288,   6,   6,   6,  32,  32,  73,  73,  73,  73,  73, 270,
       181, 181, 221, 221, 221, 221, 226, 281, 281, 149, 149, 149, 258,
       258,  43,  43,  43,  11,  11,  11,  26,  26,  26,  26, 297, 297,
       297, 154, 154, 154, 154, 202, 202, 164, 164, 164, 164, 164, 109,
       109, 109, 163, 163, 163, 163, 188, 188, 188, 188, 188,  50,  50,
        40,  40, 153, 153, 139, 139, 139, 267, 267,  91,  91,  91,   9,
         9,   9, 246, 246, 246, 246, 233, 233, 233, 239, 239, 239, 239,
        60,  60,  60,  60,  88,  88, 263, 263, 263,  79,  79,  79,  79,
        79, 193, 193, 193, 138,  56,  56, 209, 339, 339, 339, 339, 232,
       232, 232, 259, 259, 259, 337, 337, 337,  61,  61,  75,  75, 185,
       185, 185, 185,  53,  53,  53,  53, 275, 275,  39,  39, 271, 155,
       155, 290, 290, 308, 123, 123, 168, 168, 168, 168, 168, 316, 316,
       316, 316, 316, 249, 249, 225, 225, 225, 265, 265, 265, 265, 114,
       114, 346, 346, 346, 346, 346, 250, 250, 272, 272,  65,  65,  65,
        48,  48,  48,  55,  55,  55,  55,  55,  55, 269, 269,  54,  54,
        54,  54, 342,  81,  81, 125, 216, 216, 173, 173, 292, 292, 292,
       150, 150, 150, 108, 108, 162, 162, 162, 162, 162, 162, 162, 162,
       101, 101, 101, 101, 101, 295, 295, 295, 295, 295, 295, 190, 190,
       190, 256, 256, 256, 256, 302, 302,  98,  98,  98,  98,  98,  98,
       248, 248,  15,  15,  42,  42, 220, 220, 220, 220, 137, 137, 240,
       240, 240,  59,  59,  59, 129, 129, 129, 317, 317,  92,  92, 291,
       291, 158, 158, 158, 340, 340, 167, 167, 252, 252, 119, 119, 119,
       119, 147, 218, 218, 218,  20,  20,  20, 329, 329, 329, 329,  86,
        86,  86, 243, 243, 280, 289, 289,  19,  19,  19, 300, 300, 222,
       222, 326, 326, 203, 203, 203, 321, 112, 112, 112, 331, 331, 331,
        82,  82,  82, 100, 100, 304, 304, 195, 195, 323, 323, 323, 323,
       323, 323, 323, 323, 319, 319, 319, 182, 182, 182, 182, 229, 229,
       229, 230, 230, 230, 230, 318, 318, 152, 152, 152, 152, 152, 152,
       152, 160,  76, 183, 183, 183, 301, 301, 301, 293, 293,   4,   4,
         4, 254, 254, 187, 187, 187, 187, 200, 200, 200,   3,   3,   3,
       141, 118, 118, 118,  83,  83,  83,  30,  30, 177, 177, 314, 314,
       314, 314, 130, 130, 210, 210,  47, 224,  10,  93,  93,   7,   7,
         7,   7, 104, 104,  31,  31,  57,  57,  97,  97,  97,  97, 110,
       110, 110, 110, 107, 107, 126, 169, 169, 169, 169, 134, 134, 134,
       134,  80,  80,  80,  80,  51,  51,  51,  51, 105, 105, 105,  29,
        29,  29,  68,  68,  68, 142, 142, 142, 142, 206, 206,  44, 344,
       344, 127, 127, 328, 144, 144, 144,  72,  72,  72, 207, 309, 309,
       179, 179, 179, 179,  46,  46,  46,  46,  46, 283, 283, 283, 283,
       244, 284, 284, 284, 284, 284, 284, 284, 306, 306, 262, 262, 262,
       106, 106, 227, 227, 227, 227, 174, 174, 174, 174, 146, 146, 146,
       146, 146, 146,  49,  49, 242,  71,  71,  71,  71,  71,  71,  62,
        62,  63,  63,  63, 115, 115, 115, 186, 186, 186, 161, 277, 277,
       268, 268, 294, 294, 294, 213, 213, 213, 213, 213,  27, 205, 205,
       338, 338, 338,  94,  94, 307, 307,  66,  66,  14,  14,  14, 332,
       332, 332,  17,  17,  17,  17, 143, 312, 312, 312, 312, 116, 116,
       116, 131, 131, 131, 264, 264, 303, 310, 310,  74, 238,  87,  87,
        87, 296, 296, 296, 296, 296, 330, 313, 313, 201, 201, 201, 201,
       214, 279,  24,  24, 184, 247, 247, 247, 247, 198, 198,   5,   5,
         5, 334, 334, 334, 334, 334, 237, 237, 237,  64,  64, 166, 166,
       287, 287, 192, 192,  41,  41,  41,   8,  34,  22,  22,  22,  22,
       113, 113, 113, 113, 325, 325, 325, 325, 325, 325, 325, 325, 231,
       231, 231, 231, 176, 176,  18, 180, 180, 211, 211, 140, 140, 171,
       171, 171, 335, 335, 208, 208, 208, 208, 208, 208, 345, 345, 333,
       333, 333, 266, 266, 266, 266, 219, 212, 212,  23, 276, 276,  69,
        69,  69,  69,  69,  69,  69,  69,  69,  69,  89,  13,  13,  13,
       324, 324, 124, 124, 124, 124, 261, 261, 274, 274, 274, 274, 274,
       215, 215, 215,  52,  52, 135, 135, 191, 191, 191, 191, 178, 178,
       178, 178, 223, 223, 223, 223, 228, 228, 228,  99,  99,  99, 159,
       159, 159, 159, 159, 159,   0,   0,  45,  45,  45, 103, 103, 327,
       327, 327, 327, 172, 172, 172, 194, 194, 194, 305, 305,  12, 133,
       133, 133, 133, 336, 336, 336, 336,  35,  35, 111, 111, 111, 111,
        90,  90, 286, 286, 343, 343, 343, 117, 117, 117, 117, 117, 341,
       341, 299, 299,  95,  95,  95, 197, 197, 197, 197, 197, 197, 197,
       132, 132, 236, 236, 236, 236, 234, 241, 241, 241, 255, 255, 170,
       170, 170, 170, 251, 251,   2,   2,   2,   2,   2,   2,   2,   2,
        37,  37,  37,  28,  28,  28,  28, 282, 282, 282, 282, 282, 157,
       157, 157, 157, 253, 253, 253, 245, 245, 245, 156, 156, 156, 156,
       156,  16,  16, 278, 278, 260, 260, 260, 260, 260, 260, 151, 151,
       151, 151, 204, 204, 204, 204, 204, 204, 204, 273, 273, 273, 273,
       273,  96,  96,  96, 128, 121, 121, 121, 121, 121, 121, 121, 136,
        58,  58,  58, 145, 145, 145, 145, 145, 235, 235, 235,  84,  84,
        84,  84,   1, 175, 285, 285, 285,  77,  77,  38, 311, 311,  33,
        33, 322, 315, 315, 199, 199, 199, 199, 199, 196, 196, 148, 148,
       148, 148, 189, 189, 189, 189, 189, 189,  78,  78,  78,  67,  67,
        67,  67,  67,  21,  21,  25,  25,  25, 217, 120, 120, 320, 320,
       320, 320, 298, 298, 298,  36,  70,  70,  70, 102, 102, 102])

In [8]:
import numpy as np

from sklearn.model_selection import cross_validate
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import recall_score

# Feature/Target
X = df["flines"]

# Pipeline vectorizer + Naive Bayes
pipeline_naive_bayes = make_pipeline(
    TfidfVectorizer(), 
    MultinomialNB()
)

# Cross-validation
cv_results = cross_validate(pipeline_naive_bayes, X, y, cv = 5, error_score='raise')
print(cv_results)
average_recall = cv_results["test_score"].mean()
np.round(average_recall,2)

#scoring = ["recall"]

/home/rafaelincao/.pyenv/versions/3.8.12/envs/lewagon/lib/python3.8/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

{'fit_time': array([0.35668898, 0.21051693, 0.18301892, 0.19452929, 0.1874187 ]), 'score_time': array([0.03188777, 0.04299617, 0.04951715, 0.04378223, 0.04665303]), 'test_score': array([0.11 , 0.185, 0.25 , 0.235, 0.175])}

0.19